#!/usr/bin/python

name = raw_input("What is your name? ")
birthdate = raw_input("what is your birthdate? ")

age = input("How old are you? ")

print("%s was born on %s" %(name, birthdate))
print("Hwlf of your age is %s" %(age / 2))

