#!/usr/bin/python

import argparse

parser = argparse.ArgumentParser(description='Search for words including partial words')
parser.add_argument('snippet', help='partial (or complete) string to search for in the words file')

args = parser.parse_args()
snippet = args.snippet.lower()

words = open('./sample.txt').readlines()
print([word.strip() for word in words if snippet in word.lower()])
matches = []

for word in words:
    if snippet in word.lower():
        matches.append(word)
print(matches)

numbers = [1,2,3,4]
print([x*x for  x in numbers])
